openapi: 3.0.0

info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.0

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

components:
  schemas:
    Schema1:
      type: object
      properties:
        s1_p1:
          type: string
    Schema2:
      type: array
      items:
        type: string

paths:
  /path1:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                p1:
                  type: string
                p2:
                  type: number
                p3:
                  type: integer
                p4:
                  type: boolean
                p5:
                  type: array
                  items:
                    type: string
                p5_nested:
                  type: array
                  items:
                    type: array
                    items:
                      type: string
                p6:
                  type: object
                  properties:
                    p6_1:
                      type: string
                    p6_2:
                      type: number
                p6_nested:
                  type: object
                  properties:
                    p6_nested_1:
                      type: string
                    p6_nested_2:
                      type: object
                      properties:
                        p6_nested_2_1:
                          type: string
                p7:
                  oneOf:
                    - type: string
                    - type: number
                p8:
                  anyOf:
                    - type: string
                    - type: number
                p9:
                  allOf:
                    - type: object
                      properties:
                        p9_1:
                          type: string
                    - type: object
                      properties:
                        p9_2:
                          type: number
                    - $ref: '#/components/schemas/Schema1'
                p10:
                  $ref: '#/components/schemas/Schema2'
      responses:
        '200':
          description: response description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema2'